# Generated by Django 4.2.6 on 2023-10-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_votes_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='date published'),
        ),
    ]
